<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>YuexuanCrypto.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\YuexuanCrypto.Core\YuexuanCrypto.Core.csproj" />
  </ItemGroup>

  <Target Name="CopyArgon2Deps" AfterTargets="Build">
    <Copy SourceFiles="..\..\lib\Isopoh.Cryptography.Argon2.dll;..\..\lib\Isopoh.Cryptography.Blake2b.dll;..\..\lib\Isopoh.Cryptography.SecureArray.dll"
          DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>

</Project>
